# Generated by Django 5.1.1 on 2024-09-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('altitude_zone', models.CharField(max_length=100)),
                ('maturity', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yield_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('attributes', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Seed',
        ),
    ]
